# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='foodlog',
            old_name='author',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
