# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160325_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplanfood',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='api.DietPlan'),
        ),
    ]
